- name: volume-up
  ec2:
    state: present
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    region: "{{ aws_region }}"
    instance_ids: "{{ instance_id_test_ansible }}"
    key_name: id_rsa
    instance_type: t2.micro
    image: ami-4af5022c
    count: 1
    group: wordpress-test
    instance_tags:
      Name: test-ansible
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 30
  register: ec2
