##ec2
##作業マシン内にbotoが必要
- name: create ec2 instance
  ec2:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    region: "{{ AWS_REGION }}"
    key_name: id_rsa
    instance_type: t2.micro
    image: ami-4af5022c
    instance_tags:
      Name: "{{ instance_name }}"
    count_tag:
      Name: "{{ instance_name }}"
    exact_count: 1
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 8
  register: ec2

# - name: allocate EIP
#   ec2_eip:
#     aws_access_key: "{{ aws_access_key_id }}"
#     aws_secret_key: "{{ aws_secret_access_key }}"
#     region: "{{ AWS_REGION }}"
#     device_id: "{{ item }}"
#     with_items: "{{ ec2.instance_ids }}"
