# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "centos6-4"
  config.vm.box_url = "https://github.com/2creatives/vagrant-centos/releases/download/v6.4.2/centos64-x86_64-20140116.box"

  config.vm.define :web_server do |web_server|
    web_server.vm.network :forwarded_port, id: "ssh", guest: 22, host: 2222
    web_server.vm.network :forwarded_port, id: "http", guest: 80, host: 8080
    web_server.vm.network :private_network, ip: "192.168.33.10"

    web_server.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "ansible/wordpress.yml"
#      ansible.extra_vars = {
#
#      }
    end
  end
end
