- hosts: hubot
  vars_prompt:
    - name: your_name
      prompt: "君の名は?："
      default: Ryo
      private: no
    - name: your_age
      prompt: "あなたは何歳?"
      default: 24
      private: no
  become: True
  roles:
    - slack
    - input-test
  
