- name: install remi
  yum: name={{ item }} state=present
  with_items:
    - "{{ PHP_VERSION_EPEL }}"
    - "{{ PHP_VERSION_REMI }}"

- name: install php base
  yum: name={{ item }} state=present disablerepo=amzn-main enablerepo=epel
  with_items:
    - libwebp

- name: install php dependency module
  yum: name={{ item }} state=present
  with_items:
    - httpd
    - libmcrypt
    - libtool-ltdl
    - libtidy
    - libXpm
    - libtiff
    - autoconf
    - automake
    - gd-last
    - enchant-aspell

- name: install php
  yum: name={{ item }} state=present enablerepo=remi,remi-php70 disablerepo=amzn-main
  with_items:
    - php
    - php-process
    - php-mysqlnd
    - php-pecl-mailparse
    - php-json
    - php-cli
    - php-pdo
    - php-fpm
    - php-bcmath
    - php-gd
    - php-mcrypt
    - php-pecl-apcu
    - php-pecl-igbinary
    - php-pear
    - php-intl
    - php-pecl-apcu-devel
    - php-common
    - php-mbstring
    - php-xml
    - php-devel
    - php-pecl-apcu-bc
    - php-pecl-redis
    - php-opcache
    - php-enchant

#お好みで使ってください
# - name: replace php config
#   copy:
#     src: "roles/php/files/{{ item.src }}"
#     dest: "/etc/{{ item.dest }}"
#     backup: no
#     mode:
#     owner: root
#     group: root
#   with_items:
#     - { src: "php-fpm.conf", dest: . }
#     - { src: "php.ini", dest: . }
#     - { src: "php-fpm.d", dest: . }
#   notify: restart php
