- name: change instance-type
  ec2:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    region: "{{ aws_region }}"
    key_name: id_rsa
    instance_type: t2.small
    image: ami-4af5022c
    instance_tags:
      Name: "{{ instance_name }}"
    count_tag:
      Name: "{{ instance_name }}"
    exact_count: 1
    volumes:
      - device_name: /dev/xvda
        volume_type: gp2
        volume_size: 8
  register: ec2
